### ISSUE TITLE
Double page + Infinite scroll

### ISSUE THREAD

**Issue by panhartstuff** [fuzetsu/manga-loader#44]
Is there a way to have two pages side-by-side + infinite scroll? No reader have this feature for some reason. Can you please add it? Or can this be done in CSS?

**Comment by fuzetsu** [comment]
It can be done with css:
```css
.ml-images {
  display: grid;
  grid-template-columns: 1fr 1fr;
}
.ml-images img:nth-of-type(odd) {
  justify-self: right;
}
.ml-counter { display: none; }
```
Might not be perfect for every scenario but should work.

**Comment by fuzetsu** [comment]
### Improved version(s):
Right to left (like manga):
```css
.ml-images {
  direction: rtl;
  display: inline-grid;
  grid-template-columns: 1fr 1fr;
}
.ml-images img {
  margin: 0;
  margin-bottom: 10px;
}
.ml-images img:nth-of-type(odd) {
  justify-self: left;
}
.ml-counter { display: none; }
```
Left to right
```css
.ml-images {
  display: inline-grid;
  grid-template-columns: 1fr 1fr;
}
.ml-images img {
  margin: 0;
  margin-bottom: 10px;
}
.ml-images img:nth-of-type(odd) {
  justify-self: right;
}
.ml-counter { display: none; }
```
